mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
server:
  port: 8081
com:
  example:
    portfolio:
      jwt:
        secret: f4e2e52034348f86b67cde581c0f9eb5
        expire: 604800
        header: Authorization
aliyun:
  accessKeyId:
  accessKeySecret:
  bucketName:
  endPoint: 
  fileHost: 
  urlPrefix: 
spring:
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

