spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 
    username: ohno
    password: 
    hikari:
      connection-timeout: 60000
      validation-timeout: 3000
      idle-timeout: 60000
      login-timeout: 5
      max-lifetime: 60000
      maximum-pool-size: 10
      minimum-idle: 10
      read-only: false

shiro-redis:
  enabled: true
  redis-manager:
    host: 127.0.0.1:6379
